# Generated by Django 3.2.6 on 2021-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractId', models.CharField(max_length=100)),
                ('supplierId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
